name: workflow-maven-deploy

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout.
        uses: actions/checkout@v2

      - name: Step 2 - Setup Java.
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Step 3 - Maven Deploy.
        run: mvn -B deploy -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
        env:
          GITHUB_TOKEN: ${{ github.token }}
